export { default as videoIcon } from './videoIcon.svg';
export { default as chatIcon } from './chatIcon.svg';
export * from './slide';
export * from './EntryLogo';
export * from './BookIcon';
export * from './ChallengeIcon';
export * from './FinalPresentationIcon';
export * from './FireIcon';
export * from './HealthCheckupIcon';
export * from './PencilIcon';
export * from './PresentationPersonIcon';
export * from './WriteIcon';
export * from './BrainIcon';
export * from './DropDownArrow';
export * from './PostArrow';
export * from './CancelIcon';
export * from './BottomNav';
export * from './EyesIcon';
export * from './NotificationIcon';
export * from './Download';
export * from './Save';
