export * from './Landing';
export * from './NoticeDetailPage';
export * from './AdmissionOverviewPage';
export * from './FaqPage';
export * from './MyPage';
export * from './calculate';
export * from './Main';
export * from "./NoticePage"
export * from './Page404'
export * from './ErrorFixingPage'
export * from './ReturnSoon'